---
- name: 'Reload sshd'
  ansible.builtin.service:
    name:  'sshd'
    state: 'reloaded'

- name: 'Reload Apache' # grep-restart-apache-handler TODO: deduplicate?
  ansible.builtin.shell: 'apachectl configtest && apachectl graceful'

- name: 'Reload system'
  ansible.builtin.reboot:
