---
- name: 'Setup general stuff'
  ansible.builtin.import_tasks: 'setup_general.yaml'
  tags: 'general'

- name: 'Setup sshd'
  ansible.builtin.import_tasks: 'setup_sshd.yaml'
  tags: 'sshd'

- name: 'Setup Apache'
  ansible.builtin.import_tasks: 'setup_apache.yaml'
  tags: 'apache'

- name: 'Setup Docker'
  ansible.builtin.import_tasks: 'setup_docker.yaml'
  tags: 'docker'

- name: 'Setup IPv6'
  ansible.builtin.import_tasks: 'setup_ipv6.yaml'
  tags: 'ipv6'
