---
- name: 'Update Apache vhost configuration'
  ansible.builtin.template:
    src:  'vhost.j2.conf'
    dest: '/etc/httpd/conf.d/{{ server_name }}.conf'
    mode: '0644'
  notify:
    - 'Reload Apache'
